version: "3"
services:
  demo:
    image: artefactual/gearmand:latest 
    command: --queue-type=redis --redis-server=redis --redis-port=6379 --verbose=DEBUG
    ports:
    - "4731:4730"
  redis:
    image: redis
    ports:
    - "6379:6379"
  prometheus:
    image: prom/prometheus
    volumes:
    - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
  app:
    image: appscode/gearmand:0.5.2
    command: run --v=3 --storage-dir=/my-dir --addr="0.0.0.0:4730"
    volumes:
    - "./db:/my-dir"
    ports:
    - "4730:4730"
    - "3000:3000"
  client:
    image: dalongrong/client-demo
    build:
     context: ./client
  worker:
    image: dalongrong/worker-demo
    build:
     context: ./worker
  nginx:
   build: 
     context: ./openresty
   ports:
   - "8080:80"
   volumes:
   - "./openresty/app/:/opt/app/"
   - "./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
  admin:
    image: dalongrong/admin-demo
    build:
     context: ./admin
  # nodejs-client:
  #   image: dalongrong/nodejs-client-demo
  #   build: 
  #     context: ./nodejs/client
  # nodejs-worker:
  #   image: dalongrong/nodejs-worker-demo
  #   build: 
  #     context: ./nodejs/worker
  # nodejsv2-client:
  #   image: dalongrong/nodejsv2-client-demo
  #   build: 
  #     context: ./nodejsv2/client
  # nodejsv2-worker:
  #   image: dalongrong/nodejsv2-worker-demo
  #   build: 
  #     context: ./nodejsv2/worker
