apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-no-volumes.yaml -o ./k8s
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - run
        - --v=3
        - --storage-dir=/my-dir
        - --addr=0.0.0.0:4730
        image: appscode/gearmand:0.5.2
        name: app
        ports:
        - containerPort: 4730
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
