apiVersion: v1
kind: Service
metadata:
  namespace: gearman
  annotations:
    kompose.cmd: kompose convert -f docker-compose-no-volumes.yaml -o ./k8s
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  type: NodePort
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
