apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gearman
  annotations:
    kompose.cmd: kompose convert -f docker-compose-no-volumes.yaml -o ./k8s
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - image: dalongrong/worker-demo
        name: worker
        resources: {}
      restartPolicy: Always
status: {}
